spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/volleyball
    username: root
    password: 123456
  jpa:
    generate-ddl: true
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /ball


